name: Feature Request
description: Suggest an idea for phytrace
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear description of any alternative solutions or features you've considered
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Does this fit within v0.1.0 scope or is it for a future version?
      options:
        - v0.1.0 (audit-ready, reproducible, assumption-explicit)
        - v0.2.0+ (future enhancement)
        - Unsure
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        ```python
        # Example of how you would use this feature
        from phytrace import trace_run
        # ...
        ```
      render: python
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have read the Code of Conduct and agree to follow it
          required: true


